name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4     # Готовый скрипт от GitHub, который скачивает код вашего репозитория внутрь виртуальной машины
         
      - name: Login to Docker Hub

        uses: docker/login-action@v3   # Готовый официальный скрипт от Docker для прохождения авторизации
      
       
       
        with:  # Передача параметров (логина и пароля) для успешного входа
       
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest . 

      - name: Push Docker image
        run: docker push sudmanaslan/my-app:latest
